### ISSUE TITLE
Constants.swift is missing

### ISSUE THREAD

**Issue by Ricardo1980** [KentaKodashima/SampleProjectsForBlog#1]
Hi,

I tried to compile this project but the Constants.swift filie is missing.

Can you check that?

Thanks.

**Comment by JAGATBARAIYA** [comment]
I have also try this but Constants.swift file is missing.

**Comment by KentaKodashima** [comment]
I didn't include the file because sensitive data is written in the file. You need to create the file by yourself with your own Google Places API key as below.

```
import Foundation

let GOOGLE_PLACES_API_KEY = "your-api-key"
```

**Comment by JAGATBARAIYA** [comment]
Sure...Thank you for reply.
